
skillMetadata:
  sections:
    - name: Options << Name of section
      fields:
        # i don't know if it's beneficial to drag hostnames through the internet
        - name: host
          type: text
          label: The host you want to connect to
          value: ""
          placeholder: Network adress
    - name: Login << Name of another section
      fields:
        - type: label
          label: Just a little bit of extra info for the user to understand following settings
        - name: username
          type: text
          label: Username
          value: ""
        - name: password
          type: password
          label: Password
          value: ""
